import image1 from "../assets/project-1.png";
import image2 from "../assets/project-2.png";
import image3 from "../assets/project-3.png";
import image4 from "../assets/project-4.png";
import image5 from "../assets/project-5.png";
import image6 from "../assets/project-6.png";
import image7 from "../assets/project-7.png";



export const subtitle = [
    "Overview","Purpose","Scope","Use Case","Key Features"
]

export const projectData = [
  {
    slug: "joybox",
    title: "JoyBox - A Playful Collection of Classic Games",
    content:[
        "JoyBox is a playful web project that brings together three classic browser games—Tic Tac Toe, Rock Paper Scissors, and Simon Game—inside a single interactive experience. It is designed as a small entertainment platform for casual users who want quick fun without downloading any software. The site features a modern landing page with game cards, animated transitions, and a friendly interface that makes navigation simple and enjoyable. The project blends HTML, CSS, and JavaScript to create a responsive, light-weight gaming hub suitable for learning, demo purposes, and entertainment. It demonstrates front-end creativity, user interaction, and game logic in one accessible package.",
        "The primary purpose of JoyBox is to provide an entertaining and educational web-based gaming experience that showcases front-end development skills. It gives users a simple platform to play familiar games while encouraging practice in JavaScript logic, DOM manipulation, event handling, and interface design. By combining multiple games in one space, the project makes learning more engaging and memorable. It also serves as a portfolio-style project that highlights creativity, user focus, and beginner-friendly problem solving through interactive design and playful functionality. The site proves that even small web projects can be fun, practical, and valuable for demonstrating technical growth to beginners.",
        "JoyBox covers a compact scope focused on browser-based game entertainment with a polished home interface. The scope includes a landing page, three game modules, instruction panels, and basic navigation between sections. It also includes state tracking, score updates, win detection, game resets, visual feedback, and responsive layout adjustments for seamless interaction across screens. The project is intentionally limited in complexity so it remains easy to understand, maintain, and expand. This makes it ideal for learners, students, and beginners who want to explore practical front-end concepts without overwhelming project complexity while still delivering engaging gameplay and meaningful hands-on learning experiences overall.",
        "JoyBox is useful in classrooms, student portfolios, and casual entertainment settings where quick interactive games are needed. It can be used by beginners to practice JavaScript and DOM events, by teachers to demonstrate simple game logic, and by developers to present a mini-project that looks engaging and functional. The site is also suitable for informal leisure use, where users can spend a few minutes playing offline-style browser games without installation. In addition, the project supports learning by experimentation, as each game encourages users to understand rules, timing, scoring, and interaction patterns in a fun and accessible way for everyday learners.",
        "One of JoyBox’s major features is the combination of multiple classic games in one lightweight website, creating a rich, varied user experience. Each game includes clear instructions, interactive controls, real-time score updates, visual feedback, and reset options that make play intuitive. The landing page uses animated cards, hover effects, and a flexible layout to improve navigation and visual appeal. Another important feature is simplicity: it is easy to run, understand, and extend with new games or enhancements. This makes JoyBox an engaging example of front-end design, logic building, and user-centered development for learners who want entertaining web interfaces with interaction."
    ],
    image: image6,
    repo: "https://github.com/gaurav-027/joybox",
    demo: "https://joybox1.netlify.app/",
  },

  {
    slug: "airstay",
    title: "AirStay - Building a Modern Accommodation Experience",
    content:[
        "AirStay is a full-stack accommodation booking web application built with Node.js, Express, MongoDB, and EJS. It allows users to browse available rental listings, view property details, and manage their own stay recommendations through an interactive platform. The project combines authentication, flash messaging, session handling, and map-based location data to create a realistic property marketplace experience. Its design resembles a modern travel booking portal, with listing pages, user accounts, and review functionality that supports trust and discovery. The app is designed for travelers, hosts, and property seekers who want a simple way to explore, post, and evaluate accommodation options online today.",
        "The purpose of AirStay is to simplify the process of discovering and listing accommodation spaces in an easy, user-friendly digital environment. It helps travelers search for places to stay while giving property owners a platform to showcase their homes, apartments, or vacation rentals. The application encourages transparency through user reviews, secure login, and personalized experiences that make bookings informed and reliable. By combining listing management with authentication and location features, AirStay creates a complete ecosystem for property sharing. It is intended to support discovery and trust, making the rental process efficient for people planning stays, vacations, or new living arrangements.",
        "AirStay covers the complete lifecycle of a property listing experience, from posting new accommodation details to editing and deleting them when needed. The project includes user registration, secure login, session-based authentication, review submissions, and listing validation using a web stack. It supports geocoded location search, image uploads, property management, and data persistence through MongoDB. The scope also extends to flash notifications, dynamic rendering, and responsive layouts that make navigation simple. In practical terms, the app focuses on travel and rental discovery, but its architecture provides a foundation for hospitality management systems for a digital marketplace for accommodation and travel planning.",
        "AirStay is valuable for travelers seeking a dependable place to discover properties and compare options before booking. It also serves hosts who want to publish listings, share photos, and manage property details. A common use case is a user signing up, exploring available homes or apartments, and creating a review after a stay. The platform simplifies rental discovery by combining search, listing details, photos, location data, and user feedback in one place. For individuals and small property owners, it offers a practical digital venue for accommodation marketing and travel planning for short-term stays, vacations, and temporary accommodation across communities today.",
        "One of AirStay’s key features is its listing-based marketplace, where users can add detailed rental properties with descriptions, pricing, and images to attract guests. The app also includes secure authentication through Passport, ensuring that only logged-in users can create, edit, or delete listings. Review management gives users a way to rate and comment on accommodation experiences, adding credibility and helping others make better decisions. Geolocation support improves discoverability by mapping property locations, while flash messages keep users informed about account changes, successful actions, and errors. Together, these features create a smooth experience that balances usability, trust, and practical property management."        
    ],
    image: image1,
    repo: "https://github.com/gaurav-027/airstay",
    demo: "...",
  },

  {
    slug: "vidio",
    title: "VIDIO - Building a Real-Time Virtual Meeting Experience",
    content:[
        "Vidio is a full stack web application designed for simple, browser based video communication. Its React frontend provides a welcoming landing page, authentication screens, a protected home workspace, user profiles, meeting history, and dedicated meeting rooms. The Node.js and Express backend manages account registration, login, profile retrieval, and activity records through MongoDB. Socket.IO coordinates participants inside shared rooms, while WebRTC creates direct audio and video connections between browsers. Users can join with a meeting code, preview themselves, communicate with other participants, exchange chat messages, and manage media during a live session. Together, these layers deliver a focused platform for accessible meetings.",
        "The purpose of Vidio is to make online meetings approachable for people who need direct communication without a complicated workflow. Users can create an account, sign in securely, enter a meeting code, and reach a shared video room from their browser. The application reduces friction by combining identity, meeting access, live media, text chat, and recent activity in one experience. Its design emphasizes personal connection through camera and microphone support while preserving practical controls for changing media states or sharing a screen. By recording joined meeting codes, Vidio also helps users remember and revisit the meetings associated with their accounts.",
        "Vidio covers the essential workflow of a lightweight online meeting service. The frontend includes landing, login, registration, home, profile, history, protected meeting, and not found views, with navigation connecting these experiences. The backend exposes endpoints for creating users, authenticating credentials, reading profiles, saving meeting activity, and retrieving personal history. MongoDB stores user and meeting documents, while Socket.IO maintains room membership, signaling, chat delivery, and participant departures. WebRTC handles browser media exchange using a public STUN server. The current scope centers on real time meetings and account activity; it does not include recordings, scheduling, payments, moderation, or administrative management dashboards and tools.",
        "A common use case begins when a student, colleague, client, or friend creates a Vidio account and logs in. The user enters a shared meeting code on the home page, and Vidio saves that code to personal activity before opening the room. Inside the lobby, the participant supplies a display name and grants browser access to camera and microphone devices. After connecting, participants see remote video streams, exchange messages through the room chat, mute audio, disable video, or share their screen. When the conversation ends, the user returns home and can review the meeting code and date within history section.",
        "Vidio combines several practical features in one focused meeting experience. Account registration hashes passwords before storing user records, while login issues a token used for profile and activity requests. Protected pages guide authenticated users toward meeting access, profiles, logout, and history. Meeting rooms use Socket.IO for room membership, participant notifications, signaling, and persistent room chat messages. WebRTC supports live peer connections with camera and microphone streams, remote participant tiles, and automatic updates when someone leaves. Participants can toggle video and audio, share their display, send chat messages, observe unread message counts, and end calls. History preserves meeting codes and dates."    
    ],
    image: image2,
    repo: "https://github.com/gaurav-027/vidio",
    demo: "...",
  },

  {
    slug: "wanderlust",
    title: "WanderLust - Integrated Journey Planning System",
    content : [
            "WanderLust is a full-stack travel planning web application that helps users organize journeys from one platform. Users can enter their source, destination, travel dates, and number of guests, then select suitable train routes for their trip. The application generates a personalized dashboard containing transportation details, estimated expenses, weather information, destination images, nearby attractions, a map, countdown timer, and packing checklist. It combines travel search, destination discovery, budgeting, and trip preparation into a convenient digital experience.",
            "The purpose of WanderLust is to simplify the travel planning process by bringing important trip-related information together in one application. Travelers often depend on multiple websites to search for transportation, estimate costs, check weather conditions, discover attractions, and prepare their luggage. WanderLust reduces this effort by providing these services through a single platform. It helps users make informed travel decisions, organize their journey efficiently, understand expected expenses, and prepare for their destination with greater confidence.",
            "WanderLust covers user authentication, trip creation, train-route searching, transportation selection, destination information, budget estimation, weather updates, mapping, travel recommendations, packing preparation, and trip history. User and trip data are stored using MongoDB, while external APIs provide weather, photography, and location services. The current system focuses on train transportation and does not include direct ticket booking, payment processing, hotel reservations, or real-time seat availability. These features can be added in future versions.",
            "A traveler creates an account or logs into WanderLust and enters their departure city, destination, travel dates, and number of guests. The application searches for available trains for both the onward and return journeys. After selecting transportation, the traveler receives a personalized dashboard with trip details, estimated budget, weather conditions, destination photos, map location, and recommended attractions. The user can also manage a packing checklist and track preparation progress. Later, the traveler can visit their profile to review saved trips and travel history.",
            "WanderLust provides secure registration and login with encrypted passwords and session-based authentication. Users can create trips, search train routes, select onward and return transportation, and view a personalized travel dashboard. The dashboard includes destination-based budget estimation, a trip countdown, weather information from OpenWeatherMap, destination images from Unsplash, and location visualization through Mapbox. Users can explore recommended attractions, manage an interactive packing checklist, view trip history, and receive a welcome email after registration. MongoDB stores users, trips, train data, and city information."        
    ],
    image: image5,
    repo: "https://github.com/gaurav-027/wanderlust",
    demo: "...",
  },

  {
    slug: "lancerflow",
    title: "LancerFlow - An AI-Powered Freelance OS",
    content:[
            "LancerFlow is an AI-powered freelance workflow management system built with React, Node.js, Express, MongoDB, and Mongoose. It provides freelancers with one centralized platform for managing clients, projects, deadlines, budgets, notifications, profiles, and professional business documents. The application includes secure authentication, a responsive dashboard, client and project portfolios, AI-powered document generation, downloadable PDF results, and account management features.",
            "The purpose of LancerFlow is to reduce the complexity of freelance business administration. Instead of using separate tools for client records, project tracking, emails, proposals, contracts, and invoices, freelancers can manage these activities in one application. LancerFlow saves time, improves communication quality, organizes business information, and helps freelancers maintain a clearer view of their project progress and potential revenue.",
            "The system covers user registration, login, logout, JWT-based authentication, password protection, email verification, profile updates, client management, project management, notifications, dashboard reporting, and AI document generation. Users can create, edit, view, and delete clients and projects. Projects support budgets, deadlines, descriptions, and statuses such as To Do, Active, and Done. Subscription and advanced billing functionality are currently planned but not fully implemented.",
            "A freelancer can register and securely access a personal workspace. After logging in, the freelancer can add clients with contact details, create projects with budgets and deadlines, monitor project statuses, and review revenue-related dashboard information. When business communication is required, the freelancer can enter relevant details into the AI tools to generate an email, proposal, contract, or invoice. Generated documents can be copied or downloaded as PDFs, while important actions appear in the notification area.",
            "The key feature of LancerFlow is its integrated AI workspace powered by Google Gemini. It generates professional emails based on type, tone, and key points; proposals from client requirements, budget, and timeline; contracts from project terms and deliverables; and invoices from service and payment information. Additional features include protected routes, password hashing, owner-based data organization, project status tracking, client portfolios, dashboard summaries, notifications, responsive navigation, and PDF document export."
    ],
    image: image1,
    repo: "https://github.com/gaurav-027/lancerflow",
    demo: "...",
  },
  {
    slug: "manojKirana",
    title: "Manoj Kirana",
    content:[
            "Manoj Kirana is a responsive single-page React website for a local grocery business in Naugachhia, Bhagalpur, Bihar. It presents the store as a retail and wholesale supplier of daily-use groceries and FMCG products. The website includes business information, product categories, wholesale details, enquiry options, location access, opening hours, and custom grocery-themed illustrations.",
            "The purpose of the project is to establish a clear online presence for Manoj Kirana and make it easier for customers and local shopkeepers to connect with the business. It communicates the store’s retail and wholesale services, builds local trust, displays essential contact information, and directs visitors toward WhatsApp enquiries, phone calls, or store visits.",
            "The project covers a complete business showcase website rather than a full e-commerce platform. Its scope includes navigation, brand introduction, grocery categories, retail and wholesale service sections, wholesale enquiry steps, business advantages, store visuals, contact details, Google Maps access, WhatsApp messaging, phone calling, responsive layouts, animations, SEO metadata, and local business structured data.",
            "Household customers can use the website to learn about available grocery and FMCG products, check the store location, view opening hours, and contact Manoj Kirana for retail shopping information. Small retailers, kirana shop owners, and general store operators can use it to enquire about wholesale products, rates, availability, and regular stock requirements through WhatsApp or direct phone contact.",
            "The key feature is the direct connection between website content and business communication. Visitors can start pre-written WhatsApp conversations for general or wholesale enquiries, call the store, or open its Google Maps location. The website also provides a mobile-friendly menu, animated custom SVG illustrations, categorized product information, a three-step wholesale process, and structured local business data for better discoverability."
    ],
    image: image7,
    repo: "https://github.com/gaurav-027/manoj-kirana",
    demo: "https://manojkirana.netlify.app/",
  },
  {
    slug: "shortyyy",
    title: "Shortyyy - URL Shortener",
    content:[
            "Shortyyy is a backend web service that converts lengthy web addresses into compact, shareable links. The application runs on Node.js with Express, accepts JSON requests through an API route, generates unique eight-character identifiers with Nano ID, and stores URL mappings in MongoDB through Mongoose. Users submit an original address to receive a shortened code. When someone visits the code, the service looks up the corresponding record and redirects the visitor to the original destination. A root endpoint provides a basic health response, while environment variables configure the port and database connection. The current implementation is intentionally small and focused today.",
            "The purpose of Shortyyy is to simplify sharing and handling long URLs. Instead of distributing lengthy addresses containing query parameters, tracking values, or deeply nested paths, users can create a shorter identifier that is easier to copy, remember, and communicate. The server centralizes this conversion by generating a code, preserving the original destination, and resolving the code later. This approach supports cleaner messages, compact links, and convenient redirection without requiring a separate frontend. MongoDB provides persistent storage, while Express exposes the required HTTP operations. Overall, the project demonstrates the essential backend concepts behind a practical URL shortening platform for sharing.",
            "The project scope covers a focused REST-style backend for creating and resolving shortened URLs. It includes JSON request parsing, a POST endpoint for generating short links, an eight-character identifier generator, MongoDB persistence, and a GET endpoint that redirects visitors. It also includes a root response for basic server availability checking and uses environment variables for deployment configuration. The current scope does not include authentication, user accounts, custom aliases, expiration dates, click analytics, administrative dashboards, URL validation, rate limiting, frontend screens, or advanced error handling. Therefore, Shortyyy is a foundational service rather than a complete production-ready URL management product itself.",
            "A typical use case begins when a user has a long URL that needs to be shared in a message, document, social post, or application. The client sends that address as the originalUrl field in a JSON POST request to /api/shortURL. Shortyyy creates a unique code and returns it in the response. The user then shares a link containing that code. When a recipient opens the shortened path through the GET route, the server searches MongoDB, finds the saved original address, and redirects the recipient automatically. This workflow reduces link length while preserving access to the online resource for recipients.",
            "The key feature is automated URL shortening with persistent redirection. Shortyyy generates an eight-character Nano ID for each submitted address, saves the mapping between the generated code and original URL in MongoDB, and returns the code after successful creation. Its redirect endpoint accepts the code as a path parameter, retrieves the matching document through Mongoose, and sends the visitor to the stored destination. Express JSON middleware enables straightforward API communication, and environment variables allow the server port and MongoDB connection string to change between environments. A health endpoint also gives developers a way to confirm that the server is running."
    ],
    image: image1,
    repo: "https://github.com/gaurav-027/shortyyy",
    demo: "...",
  },
  {
    slug: "g27",
    title: "G27 - My Portfolio Website",
    content:[
      "G27 is a modern personal portfolio website designed to present Gaurav Kumar as a full stack MERN developer. It combines bold visual storytelling, motion effects, a clean layout, and project-based storytelling to showcase technical expertise, creativity, and professional ambition. The site highlights the developer’s identity, skill stack, work philosophy, and selected projects in a polished digital format. Built using React, Vite, GSAP, and modern frontend techniques, it offers an immersive browsing experience that feels both premium and highly engaging for recruiters, clients, and collaborators. It is crafted to communicate trust, capability, and a strong appetite for real-world digital problem solving.",
      "The website exists to create a professional online presence for Gaurav Kumar and make his skills visible to employers, clients, and collaborators. It acts as a digital introduction, presenting a clear story of capability, consistency, and creativity. Rather than simply listing technologies, it demonstrates how design, logic, and execution work together in real projects. The portfolio helps turn interest into opportunity by showing technical depth, work quality, and problem-solving mindset in a way that is visually compelling and easy to understand. Recruiters can evaluate expertise quickly, while businesses gain confidence in the developer’s reliability, communication, and execution potential for projects.",
      "The project covers the complete front-end experience of a developer portfolio, including the landing page, about section, skills presentation, project showcase, and contact call-to-action. It is designed as a single-page experience with animated transitions, layered visuals, and interactive design elements that enhance engagement without sacrificing clarity. The scope also includes a strong narrative structure, personal branding, and responsive behavior across devices. This makes the site suitable for portfolio viewing on desktop, tablet, and mobile screens while maintaining a premium and modern identity. It also supports recruiter discovery, portfolio storytelling, technical credibility, and smooth navigation for all audiences and business contexts.",
      "This portfolio is intended for recruiters, hiring managers, startups, and clients seeking a capable full stack developer. When someone visits the site, they can quickly understand the developer’s capabilities, areas of expertise, and style of work through a visually rich and structured layout. It can also help during freelance outreach, job applications, or client proposals by making a strong first impression. A user can navigate project sections, review technical skills, and identify relevant experience without needing additional context or explanations. The site works as a digital resume, business card, and project gallery, creating trust and helping decision-makers assess fit efficiently.",
      "A standout element of the website is its visually dynamic interface, powered by GSAP animations and layered motion design. The portfolio uses custom character visuals, marquee text, and scroll-driven transitions to create a memorable browsing experience without compromising readability. It also organizes developer information into clearly defined sections, helping visitors absorb skills, personality, and project work quickly. Additional value comes from its modern front-end stack, responsive layout, and immersive styling, which combine to present the developer as innovative, capable, and ready for real-world challenges. These features improve presentation, engagement, and brand perception while communicating technical confidence and creative execution effectively."
    ],
    image: image3,
    repo: "https://github.com/gaurav-027/g27",
    demo: "https://g27.onrender.com/",
  }
]